### ISSUE TITLE
Y-axis tick marks are goofy for some depth profile plots

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#15]
A list of stations for which the y-axis tick marks are goofy:

- [x] 424840088241600 (Beulah Deep)

- [x] 424929088231300 (Beulah Station 2)

- [x] 432224088154900 (Big Cedar South)

- [x] 423556088365001 (Delavan Center)

- [x] 434928088570000 (Green East)

- [x] 430551088273500 (Oconomowoc Deep)

- [x] 430609088262200 (Oconomowoc Hewitt Point)

- [x] 424915088083900 (Wind)  This site also has a different y-axis max/min for the first date...can we standardize this?

![image](https://cloud.githubusercontent.com/assets/10731242/14685688/24ec215c-06fb-11e6-9a17-e0008086cbd3.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS can you describe this issue a little more? What is goofy about them?

**Comment by sbmarsh-USGS** [comment]
In the last three plots, the y-axis has minor tick marks that look unevenly spaced...i.e., minor tick marks real close to the 4, 8, and 12 and then the others are farther apart.

**Comment by lindsaycarr** [comment]
The funky tick spacing must have been an issue with the previous gsplot code, but it is fixed with v0.5.4 and greater. @sbmarsh-USGS test this issue by using gsplot v0.5.4. Run this line to install that version: `devtools::install_github('USGS-R/gsplot', ref='v0.5.4')`

Each plot will have the same y-axis values now, see #38 for changes

**Comment by sbmarsh-USGS** [comment]
Looks great!
