### ISSUE TITLE
stagehydrographs - dates are read in as numbers from files

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#68]
First saw this issue with Wind Lake. I will email the file.

**Comment by lindsaycarr** [comment]
This appears to be because of the file extension. From what I can see, Wind is the only file that has a `.xls` instead of `.xlsx`. When I convert the file to `.xlsx` and update the csv of filenames, it works.

Here's what I get:

![image](https://cloud.githubusercontent.com/assets/13220910/26423580/ce0e1e84-4093-11e7-908e-8de99824b8bf.png)
