### ISSUE TITLE
No tick marks or dates (years) on x-axis on Winnebago stage hydrograph

### ISSUE THREAD

**Issue by sbmarsh-USGS** [USGS-R/lakeReport#88]
This is the only plot for which this happened.  Perhaps due to the number of years?...134 years.  1882-2016
Winnebago at Oshkosh (04082500)

![image](https://user-images.githubusercontent.com/10731242/40136024-5f2143e2-590c-11e8-921b-566f0c37d1d4.png)

**Comment by lindsaycarr** [comment]
@sbmarsh-USGS merely a fluke in my classes for dates and it is very specific to this site. 

This line used the class `Date` https://github.com/USGS-R/lakeReport/blob/master/R/functions-stagehydrograph.R#L41, but the rest uses `POSIXct` for the dates https://github.com/USGS-R/lakeReport/blob/master/R/functions-stagehydrograph.R#L47-L51. So, it is not able to figure out where to put the ticks because we have mixed data classes. All you should need to do is change the `as.Date` on this line https://github.com/USGS-R/lakeReport/blob/master/R/functions-stagehydrograph.R#L41 to `as.POSIXct` and it should work.

**Comment by sbmarsh-USGS** [comment]
@lindsaycarr That did the trick!  Thank you!
